.gitignore, examples/gpu/eemumu_AV/SubProcesses/Makefile
simple changes in .gitignore for performance data and change in the Makefile to fix debug builds for cuda files
=> Stefan infra2

.gitignore
little change in .gitignore for params files for performance testing
=> ignore local params files

epoch1/cuda/gg_ttgg/src/HelAmps_sm.cu, epoch1/cuda/gg_ttgg/src/rambo.cc
This patches a couple of small typos/syntax errors I noticed trying to compile
=> Fix minor syntax errors

.github/workflows/newissues2lounge.yml
taken from https://github.com/qmacro/action-add-issue-to-project-column
thanks @hageboeck
=> macro to add newly created issues automatically to the Lounge project

epoch1/sycl/ee_mumu/CMakeLists.txt, epoch1/sycl/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc, epoch1/sycl/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.h, epoch1/sycl/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc, epoch1/sycl/ee_mumu/src/mgOnGpuConfig.h, epoch1/sycl/ee_mumu/src/rambo.cc, epoch1/sycl/ee_mumu/src/rambo.h
PR #86 did not actually contain the updated code and was just a copy of the CUDA version. This PR includes the changes to support SYCL and has also been updated to support [OneAPI 2021.1.1](https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpc-c-compiler-release-notes.html).
=> Updated to Intel OneAPI 2021.1.1

epoch1/cuda/ee_mumu/SubProcesses/Makefile, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc, epoch1/cuda/ee_mumu/src/Makefile, epoch1/gridpack/eemumu/madevent/Source/make_opts
Add a few comments about build options
(and also a test of restrict, with no impact)
=> Add a few comments about build options

epoch1/cuda/ee_mumu/SubProcesses/Makefile, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh, epoch2/cuda/ee_mumu/SubProcesses/Makefile, epoch2/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc, epoch2/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc, epoch2/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh, epoch2/cuda/ee_mumu/src/mgOnGpuConfig.h
A few more patches for clang11, before merging vectorization (which still has some issues for clang)
=> A few more patches for clang11

epoch1/cuda/ee_mumu/SubProcesses/Makefile, epoch1/cuda/ee_mumu/src/Makefile
=> Add support for ccache

epoch1/cuda/ee_mumu/SubProcesses/Makefile, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.h, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/runTest.cc, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh, epoch1/cuda/ee_mumu/src/HelAmps_sm.cc, epoch1/cuda/ee_mumu/src/mgOnGpuConfig.h, epoch1/cuda/ee_mumu/src/mgOnGpuTypes.h, epoch1/cuda/ee_mumu/src/mgOnGpuVectors.h, epoch1/cuda/ee_mumu/src/rambo.cc, test/Makefile
This implement the last bits of vectorization for color agebra and related things discussed in issue #178 
Since it involved a few changes to operators for complex and vector types, I also tested again cucomplex and added a few new fixes that became necessary with the changes in the code in the last few months
=> Vectorize color algebra + Fixes for cucomplex

epoch1/cuda/ee_mumu/SubProcesses/profile.sh
… analysis
Also add a samll fix in that script (add an explicit make)
=> [warps] add the divergence metrics also to the profile script for GUI analysis

.github/workflows/c-cpp.yml, epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
This addresses #214 for eemumu.
=> Add float compilation to CI for epoch1

epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
just a minor change in throughput12.sh, useful for the hetklas branch
=> [amd] minor patch if AVX512 is not supported

tools/plotwavedep_examples/gg_tt_wavefuncs_raw.txt
small pr to add a missing file to compute wave function dependencies for gg->ttgg
=> add missing example file

tools/gpuprops.cu
little tool to extract gpu card properties
=> WIP - extract gpu properties

epoch2/sycl/ee_mumu/CMakeLists.txt, epoch2/sycl/gg_ttgg/CMakeLists.txt
=> added fast math flag

epochX/sycl/gg_ttgg/src/Parameters_sm.cc, epochX/sycl/gg_ttgg/src/mgOnGpuTypes.h, epochX/sycl/gg_ttgg/src/mgOnGpuVectors.h
=> Adding << operator for complex numbers

epochX/sycl/README.md
This resolves issues #234 and #235. The information should be in documentation, not the issue tracker.
=> Added SYCL Docs

epochX/sycl/gg_ttgg/src/mgOnGpuTypes.h
=> Now builds with fastmath

.gitignore
=> ignore top level include directories

epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.common, epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile
Fix confusing errors about googletest from 'make -f cudacpp -pn' for benchmarking containers
This fixes #507
=> Fix confusing errors about googletest from 'make -f cudacpp -pn' for benchmarking containers

epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.common, epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile
Fix the previous patch #508 for bmk, addresses again #507
=> Fix the previous patch for bmk

epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.common, epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk, epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile, epochX/cudacpp/ee_mumu.sa/CODEGEN_cudacpp_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_tt.mad/SubProcesses/makefile, epochX/cudacpp/gg_tt.sa/CODEGEN_cudacpp_gg_tt_log.txt, epochX/cudacpp/gg_tt.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttg.sa/CODEGEN_cudacpp_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttgg.sa/CODEGEN_cudacpp_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttggg.sa/CODEGEN_cudacpp_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/heft_gg_h.sa/CODEGEN_cudacpp_heft_gg_h_log.txt, epochX/cudacpp/heft_gg_h.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/tput/throughputX.sh
Additional patches for benchmarking
So far: add distclean to madevent makefiles
=> Additional patches for benchmarking

epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk, epochX/cudacpp/ee_mumu.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/ee_mumu.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_tt.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttgg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttgg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttggg.mad/SubProcesses/cudacpp.mk, epochX/cudacpp/gg_ttggg.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/heft_gg_h.sa/SubProcesses/cudacpp.mk, epochX/cudacpp/tput/throughputX.sh, tools/Makefile
Additional fixes and features for the bmk project
- add yet another protection for googletest in parallel builds (in throughputX.sh)
- fix throughputX.sh to allow multiple processes
- add a BMKMULTIPLIER for the number of iteration in all processes
- cleanup: remove tools/Makefile which is not needed (cleaning up happens in test)
=> Additinal fixes and features for the bmk project

epochX/cudacpp/tput/simdSymSummary.sh, epochX/cudacpp/tput/throughputX.sh
Minor fixes in bmk scripts
Avoid erros from simdSymSummary on a read only filesystem
=> Minor fixes in bmk scripts

epochX/cudacpp/tput/throughputX.sh
add BMKEXEARGS to allow BMK containers to change blocks and threads
=> add BMKEXEARGS to allow BMK containers to change blocks and threads

epochX/cudacpp/tput/throughputX.sh, tools/benchmarking/bmkplots.py, tools/benchmarking/plots/ggttgg.2022/pmpe.txt
Additional features for benchmarking
Add BMKEXEARGS
Use six degimal digits and dump to file the pmpe04 tests
=> Additional features for benchmarking

epochX/sycl/README.md
Add an example of compiling with the Intel-supplied Docker image.
=> Add Docker image example to README for SYCL version

epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/runTest.cc, epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.mad/SubProcesses/runTest.cc, epochX/cudacpp/ee_mumu.sa/CODEGEN_cudacpp_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.sa/SubProcesses/runTest.cc, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/SubProcesses/runTest.cc, epochX/cudacpp/gg_tt.mad/src/Parameters_sm.h, epochX/cudacpp/gg_tt.sa/CODEGEN_cudacpp_gg_tt_log.txt, epochX/cudacpp/gg_tt.sa/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.mad/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttg.sa/CODEGEN_cudacpp_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.sa/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.mad/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttgg.sa/CODEGEN_cudacpp_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.sa/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.mad/SubProcesses/runTest.cc, epochX/cudacpp/gg_ttggg.sa/CODEGEN_cudacpp_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.sa/SubProcesses/runTest.cc, epochX/cudacpp/heft_gg_h.sa/CODEGEN_cudacpp_heft_gg_h_log.txt, epochX/cudacpp/heft_gg_h.sa/SubProcesses/runTest.cc
=> Fix bug in runTest.cc (add devGs and copy the array from hstGs)

.gitignore
Tiny PR to ignore visual studio code config directory .vscode
=> ignore visual studio config dir

epochX/cudacpp/gg_tt01g.mad/CODEGEN_mad_gg_tt01g_log.txt, epochX/cudacpp/gg_tt01g.mad/SubProcesses/P2_gg_ttxg/.gitignore, epochX/cudacpp/gg_tt01g.mad/SubProcesses/P2_gg_ttxg/counters.cc, epochX/cudacpp/gg_tt01g.mad/SubProcesses/P2_gg_ttxg/fbridge_common.inc, epochX/cudacpp/gg_tt01g.mad/SubProcesses/P2_gg_ttxg/ompnumthreads.cc
Bug fix: add missing files to gg_tt01g.mad in the repo
This fixes some issues in MR #676 where I had forgotten some files
=> Bug fix: add missing files to gg_tt01g.mad in the repo

epochX/cudacpp/CODEGEN/MG5aMC_patches/PROD/patch.P1, epochX/cudacpp/CODEGEN/MG5aMC_patches/PROD/patch.common, epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt, epochX/cudacpp/ee_mumu.mad/Source/makefile, epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile, epochX/cudacpp/ee_mumu.sa/CODEGEN_cudacpp_ee_mumu_log.txt, epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt, epochX/cudacpp/gg_tt.mad/Source/makefile, epochX/cudacpp/gg_tt.mad/SubProcesses/makefile, epochX/cudacpp/gg_tt.sa/CODEGEN_cudacpp_gg_tt_log.txt, epochX/cudacpp/gg_tt01g.mad/CODEGEN_mad_gg_tt01g_log.txt, epochX/cudacpp/gg_tt01g.mad/Source/makefile, epochX/cudacpp/gg_tt01g.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt, epochX/cudacpp/gg_ttg.mad/Source/makefile, epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttg.sa/CODEGEN_cudacpp_gg_ttg_log.txt, epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt, epochX/cudacpp/gg_ttgg.mad/Source/makefile, epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttgg.sa/CODEGEN_cudacpp_gg_ttgg_log.txt, epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt, epochX/cudacpp/gg_ttggg.mad/Source/makefile, epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile, epochX/cudacpp/gg_ttggg.sa/CODEGEN_cudacpp_gg_ttggg_log.txt, epochX/cudacpp/gq_ttq.mad/CODEGEN_mad_gq_ttq_log.txt, epochX/cudacpp/gq_ttq.mad/Source/makefile, epochX/cudacpp/gq_ttq.mad/SubProcesses/makefile, epochX/cudacpp/gq_ttq.sa/CODEGEN_cudacpp_gq_ttq_log.txt, epochX/cudacpp/heft_gg_h.sa/CODEGEN_cudacpp_heft_gg_h_log.txt
ensure that 'make cleanall' is propagated to all P* directories
this fixes #702
=> ensure that 'make cleanall' is propagated to all P* directories

epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/MatrixElementKernels.cc, epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/process_function_definitions.inc
minor fixes (clang format and code comments)
=> minor fixes (clang format and code comments)

.github/workflows/testsuite_oneprocess.sh
Port to master a CI fix (tmad xsec tolerance increase for #889) from master_june24 work in WIP PR #882
=> Port to master a CI fix (tmad xsec tolerance increase for 889) from master_june24 work

epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/AUTHORS
Hi @oliviermattelaer @roiser ok for this?
Thanks Andrea
=> In AUTHORS, add  Filip Optolowicz to the Collaborators section
