madgraph5/madgraph4gpu

- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
Minor change to remove warnings created by `system()`, replacing it with `execlp`.
> Fixed warnings during compilation by replacing system with execlp

- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/perf/perf.py
- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/timermap.h
(cherry picked from commit f25e0bdf332382fdea384fdd4aba6593355ebb52)
change gcheck.exe to write the json info as late as possible (including the tear down processing times). Add those individual times to the json file
add two new plots for perf.py to print performance data in 2D with the same number of threads being the same color and size of circle on the plot. 
Another plot shows bar graphs of the timings for various numbers of blocks with fixed number of threads.
> change performance plotting in cuda file and python

- examples/gpu/eemumu_AV/SubProcesses/Makefile
- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- examples/gpu/eemumu_AV/src/mgOnGpuConfig.h
- examples/gpu/eemumu_AV/src/rambo.cc
- tools/CommonRandomNumbers.h
- Add a header in `tools/` for creating reproducible common random numbers using c++11.
- Modify eemumu_AV such that it can make use of those.
Note that to increase the compiler coverage and to decrease the probability of errors, this uses
```
#define FLAG true/false
...
if (FLAG)
```
This way, the compiler checks both code paths for correct syntax, but no assembly is generated for the inactive path.
> Add feature to produce common random numbers.

- examples/gpu/eemumu_AV/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
I wanted to test if memory / resource management can be automated. With unique_ptr and a few helper functions, a lot of `ifdef` and `delete[] / free`s can be removed. Is this helpful for us?
> [eemumu_AV] Use unique_ptr and RAII to automate memory management.

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/src/Makefile
- epoch1/cuda/ee_mumu/src/mgOnGpuConfig.h
- epoch1/cuda/ee_mumu/src/rambo.cc
- epoch1/cuda/ee_mumu/src/rambo.h
This disentangles testing and compilation without CUDA that was previously in #50 
In order to have automated tests, implement the following:
- Allow for setting compiler options from outside the Makefile using `MGONGPU_CONFIG=<option>`
- Make CPU version compile without cuda (requires `make MGONGPU_CONFIG=-DMGONGPU_COMMONRAND_ONHOST`,  `export MGONGPU_CONFIG=-DMGONGPU_COMMONRAND_ONHOST` or similar)
- When no cuda toolkit is found, the Makefile only compiles the CPU version. (also requires `-DMGONGPU_COMMONRAND_ONHOST` to not interfere with the default settings.)
> [eemumu epoch1] Make code compile without CUDA

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
As described in #73 this is a spinoff of #72
> BUG FIX in PR #47: arrays were uninitialised in RAII constructors

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/src/Makefile
Reorganise Makefiles to prepare it for addition of tests.
(This version of the makefile runs already in #52, but took here a separate PR for easier reviewing).
- Remove hard-coded CUDA paths. Instead, react to CUDA_HOME if exported.
- Replace "cd xxx && make" by the more standard "make -C".
- If no nvcc is found and no MGONGPU_CONFIG is given, automatically switch to C++ random numbers.
This allows for compiling the CPU-only code.
- Separate optimisation flags from other C++ flags. This facilitates
switching between debug and optimised builds, because only one variable needs to be overwritten.
- Protect all cuda-related variables with a conditional, so the
corresponding targets don't get built.
Fixes #55.
> [ep1 cuda eemm] Make Makefiles more installation independent.

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/src/Makefile
- Fix #103, race condition in parallel for
- Fix missing include
- Fix compilation with clang.
**Note**:
Although this fixes a race condition, we can potentially still get different results in dependence of number of threads, namely if analysing events 0-9 and computing good helicities will give a different result than analysing events 100-109, for example.
I think that the physics should be robust against that, but I'm not 100% sure.
That's probably not a problem, though, since when starting 2 madgraph processes with different random numbers, you are in the same situation: Helicities get computed from different events.
> Fix race condition in omp parallel for

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
Since the debug target was overwriting the flags for nvcc, the tests
would not build when invoking the debug target.
Fix #105.
> [ep1 cuda eemm] Fix cuda flags in debug build.

- test/Makefile
Minor issue: 'make distclean' fails if called twice in a row
> Fix 'make distclean' - the second 'make distclean fails

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.h
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
A minor patch to dump the gcc and nvcc version of the ME calculation module.
Note that there is a factor 2 in the C++ between gcc8 and gcc9.
> Dump the gcc and nvcc version

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/src/Makefile
Enable C++-only builds on a systema which does have nvcc
It is enough to "export CUDA_HOME=invalid" and only the C++ will be built
This enables emulating the CI tests
> Enable C++-only builds on a system which does have nvcc

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.h
This patch fixes two build warnings (unused variables) and especially a link error for runTest.exe.
```
/cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/bin/clang++  -O3  -std=c++11 -I. -I../../src -I../../../../../tools -DUSE_NVTX -Wall -Wshadow -Wextra -fopenmp  -ffast-math  -I/usr/local/cuda-11.0/include/ -c CPPProcess.cc -o CPPProcess.o
In file included from CPPProcess.cc:444:
./CPPProcess.h:89:9: warning: private field 'm_numiterations' is not used [-Wunused-private-field]
int m_numiterations;
^
./CPPProcess.h:103:14: warning: private field 'amp' is not used [-Wunused-private-field]
cxtype** amp;
^
2 warnings generated.
/cvmfs/sft.cern.ch/lcg/releases/clang/10.0.0-62e61/x86_64-centos7/bin/clang++ check.o -o check.exe CPPProcess.o  -O3  -std=c++11 -I. -I../../src …
```
> Minimal changes to add clang support

- epoch2/cuda/ee_mumu/SubProcesses/Makefile
- epoch2/cuda/ee_mumu/src/Makefile
This is the same for epoch2 as PR #133 was for epoch1
It is needed to fix the CI test failure in the initial PR #140 version
> [epoch2] Enable C++-only builds on a system which does not have nvcc

- epoch2/cuda/gg_ttgg/SubProcesses/Makefile
This is a minimal change to allow that the code runs out of the box for Carl Vuosalo's team.
Anyway epoch2 was already running out of the box.. not bad!
PS This fixes the build issue that was there before (not sure why it was [saying it was?] removing googletest?)
```
make[1]: Entering directory `/afs/cern.ch/user/a/avalassi/GPU2020/madgraph4gpuTer/tools'
rm -rf googletest
make[1]: Leaving directory `/afs/cern.ch/user/a/avalassi/GPU2020/madgraph4gpuTer/tools'
make -C ../../../../../tools/
make[1]: Entering directory `/afs/cern.ch/user/a/avalassi/GPU2020/madgraph4gpuTer/tools'
rm -rf googletest
make[1]: Leaving directory `/afs/cern.ch/user/a/avalassi/GPU2020/madgraph4gpuTer/tools'
/cvmfs/sft.cern.ch/lcg/releases/gcc/9.2.0-afc57/x86_64-centos7/bin/g++  -O3 -std=c++11 -I. -I../../src …
```
> [ggttgg ep2] Workaround: disable test builds

- .github/workflows/c-cpp.yml
- epoch1/cuda/ee_mumu/src/Makefile
- epoch2/cuda/ee_mumu/src/Makefile
This is related to issue #139: once I merge epoch2 into epoch1, the latter will be my main reference. However only epoch2 is tested on the GPU so far. Here I am adding epoch1 to GPU tests too.
This probably depends on issue #138 being fixed. I think we need gcc9 to build (not sure if immediately or only when vectorization is there). I will open this as a WIP PR so that the CI can get tested.
> [tests] Add epoch1_eemumu_GPU and use gcc9 in the CI

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/src/Makefile
- epoch1/cuda/ee_mumu/src/mgOnGpuVectors.h
- epoch1/cuda/ee_mumu/src/rambo.cc
Clarify issues with cxtype_ref on gcc/clang + Test clang11.1 and clang12.0
This addresses a mix of two related issues
- issue #172 about cxtype_ref: understood as not a bug, it depends on common rancom numbers (needed for clang11, 12 as cuda11 does not support them)
- issue #182 about testing the latest clang11.1 and clang12.0 with openmp support (removed the hack for clang 11.0 with no openmp in the cvmfs install I use)
> Clarify issues with cxtype_ref on gcc/clang + Test clang11.1 and clang12.0

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
This is mainly about adding perf stat to allow a better analysis of AVX512 and other vectorization scenarios (issue #173)
This assumes that perf stat works - which I am able to do on itscrd03, and for my older itscrd70 will come after solving issue #180 (a hard reboot of the VM)
I also added a few minor patches to sytreamline printouts
> Add perf stat to the throughput script + Minor patches to streamline printouts

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
This includes a fix for a gcc8/OMP issue reported by both @roiser and @lfield 
I suggest we stick to gcc9.2 or above, but I fixed this and another gcc8 issue (with #ifdef that depend on __GNUC__)
> A few fixes for lxplus (T4) and for gcc8

- epoch2/cuda/gg_ttgg/SubProcesses/Makefile
- epoch2/cuda/gg_ttgg/src/HelAmps_sm.cu
Two bug fixes in the ME calculation
- first (fix issue #198, cuda and C++ were giving different results, now fixed): avoid using "abs" for floats, this truncates to integers
- second (changes both CUDA and C++ in the same way): the handling of energy and mass in ixxxxx was different from that in the Fortran, I now am using the Fortran version as in epoch1 eemumu... @oliviermattelaer can you please cross check and comment? otherwise I would have to fix it also in epoch1 eemumu (an dthen for upstream posrts)
In addition, a third bug fix in the Makefile, the code must be recuit if HelAmps changes
> [ggttgg] two functional bug fixes in the ME calculation and one in the Makefile

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/SubProcesses/profile.sh
- epoch2/cuda/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/gcheck_sa.cu
@roiser @oliviermattelaer this is related to what we discussed during the last week
I am adding a cudaDeviceSynchronize between sigmakin and the copy of ME from device to host
The overall throughput does not change (*), while the relative split of sigmakin and copyDtoH changes enormously. Now it is clear that the copy takes around the same time as the sigmakin calculation for eemumu, while for ggttgg it is totally negligible with respect to it.
(*) NB: I am observing big fluctuations on the VM, and they actually come from the copy, while the calculation is rather stable. For eemumu this transaltes into large fluctuations (between 6.0 and 6.5E8, lower than the usual 7.3E8 that it should be). This is discussed in https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillme …
> [devsync] add cudaDeviceSynchronize for better timing measurements

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
Two changes
- improve the profiling script to also measure cuda thread divergence
- add the option to artificially introduce some thread divergence in eemumu, just to check what it does
This essentially resolves issue #25, using command line profiling rather than GUI profiling
> [warps] measure cuda thread divergence

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/SubProcesses/timermap.h
- epoch1/cuda/ee_mumu/src/mgOnGpuConfig.h
Add MECalc-only throughput (no DtoH copy) as discussed in issue #22 
Another minor change, increase ntpbMAX to 1024 (was 256, but 512 works without issues on a V100)
> Add MECalc-only throughput (no DtoH copy)

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/src/Makefile
This started off as a followup of issues reported by @hageboeck on itscrd04
- After an upgrade of clang from 10 to 11 by puppet, things no longer worked: he fixed it by upgrading cuda from 11.1 to 11.3 on his machine: he fixed i
- On my side however, using cvmfs clang, clang11.1 did not work because it was setup with gcc 10.3: I fixed it by downgrading the setup to gcc 10.2 (thanks to Dima, https://sft.its.cern.ch/jira/browse/SPI-1924)
As a followup:
- I understood there is a toolchain in clang and found a way to dump it (actually I am dumping the gcc used to build libgcc.a)
- As I was there, I also dumped the gcc/clang version used by nvcc
- I realised that nvcc with clang was NOT using clang, because "-ccbin" was missing, so I added that
- After adding that, nvcc builds did change and …
> FIXES for clang: dump gcc toolchain and ensure nvcc actually uses it

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/src/Makefile
First patch for Marconi M100 (Power9+A100) issue #223 
- Disable vectorization in C++, need to understand better the hardware and the compiler
- Port throughput12.sh script (different /proc/cpuinfo, different nvidia-smi, different ncu...)
> First patch for Marconi M100 (Power9+A100)

- test/Makefile
- test/src/MadgraphTest.cc
Upgrade googletest from 1.10.0 to 1.11.0
This is needed to port to gcc11.1 and avoid [-Werror=maybe-uninitialized]
A small fix in a test .cc is also required (fixed using the advice by googletest)
> Upgrade googletest from 1.10.0 to 1.11.0

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/CPPProcess.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/simdSym.sh
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/simdSymSummary.sh
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/testxxx.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/src/HelAmps_sm.cc
- epoch1/cuda/ee_mumu/src/Makefile
- epoch1/cuda/ee_mumu/src/mgOnGpuConfig.h
- test/Makefile
This is another patch for issue #229. The idea is to recover some of the LTO benefits with code changes such as inlining, rather than with the -flto build flag.
> Various LTO tests (emulate LTO by inline, use -flto only on one file, etc)

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
Interesting, first time I see AVX512z better than AVX512y...
Unfortunately I have no perf to chech better
```
On cori04 [CPU: Intel(R) Xeon(R) Gold 6148 CPU] [GPU: 1x Tesla V100-SXM2-16GB]:
=========================================================================
Process                     = EPOCH1_EEMUMU_CUDA [nvcc 11.4.48 (gcc 10.1.0)]
FP precision                = DOUBLE (NaN/abnormal=0, zero=0)
EvtsPerSec[MatrixElems] (3) = ( 7.520234e+08                 )  sec^-1
EvtsPerSec[MECalcOnly] (3a) = ( 1.425600e+09                 )  sec^-1
MeanMatrixElemValue         = ( 1.371706e-02 +- 3.270315e-06 )  GeV^0
TOTAL       :     0.542458 sec
real    0m0.663s
==PROF== Profiling "sigmaKin": launch__registers_per_thread 122
==PROF== Profiling "sigmaKin": …
```
> CORI tests - first performance benefit of AVX512/zmm

- epoch1/cuda/ee_mumu/SubProcesses/Makefile
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/check.cc
- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
- epoch1/cuda/ee_mumu/src/Makefile
- epoch1/cuda/ee_mumu/src/mgOnGpuConfig.h
…t aggressive inlining
```
On itscrd70.cern.ch [CPU: Intel(R) Xeon(R) Silver 4216 CPU] [GPU: 1x Tesla V100S-PCIE-32GB]:
=========================================================================
Process                     = EPOCH1_EEMUMU_CUDA [nvcc 11.4.48 (gcc 9.2.0)] [inlineHel=0]
FP precision                = DOUBLE (NaN/abnormal=0, zero=0)
EvtsPerSec[MatrixElems] (3) = ( 7.212939e+08                 )  sec^-1
EvtsPerSec[MECalcOnly] (3a) = ( 1.400295e+09                 )  sec^-1
MeanMatrixElemValue         = ( 1.371706e-02 +- 3.270315e-06 )  GeV^0
TOTAL       :     0.849224 sec
2,808,114,769      cycles                    #    2.588 GHz
3,905,267,544      instructions              #    1.39  insn per cycle
1.153374486 seconds time elapsed
==PROF== Profiling "sigmaKin": …
```
> Simultaneous builds and tests with and without inlining

- epoch1/cuda/ee_mumu/SubProcesses/P1_Sigma_sm_epem_mupmum/throughput12.sh
Minor patches for AMD (only in the throughput script essentially)
Interesting performance, even in inline mode.
This AMD does not yet have AVX512 (it is a zen3 not a zen4?)
```
On b7s01p3272.cern.ch [CPU: AMD EPYC 7302 16-Core Processor] [GPU: none]:
=========================================================================
Process                     = EPOCH1_EEMUMU_CPP [gcc 9.2.0] [inlineHel=0]
FP precision                = DOUBLE (NaN/abnormal=0, zero=0)
Internal loops fptype_sv    = SCALAR ('none': ~vector[1], no SIMD)
Random number generation    = COMMON RANDOM (C++ code)
OMP threads / `nproc --all` = 1 / 64
EvtsPerSec[MECalcOnly] (3a) = ( 1.790062e+06                 )  sec^-1
MeanMatrixElemValue         = ( 1.372113e-02 +- 3.270608e-06 )  GeV^0
TOTAL       :     5.262333 sec …
```
> Tests on an AMD EPYC node

- epochX/sycl/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/CPPProcess.cc
- epochX/sycl/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/CPPProcess.h
- epochX/sycl/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc
Fix for Issue #260. The variables cIPC and cIPD following the same method as cHel.
> Fix for hardcoded cIPC and cIPD

- epochX/sycl/gg_ttgg/SubProcesses/P1_Sigma_sm_gg_ttxgg/check_sa.cc
1. changed device selection to better handle multiple devices with same vendor id
2. Fixes #294 
3. free device memory to prevent memory leaks
4. some small structural changes for includes as workaround for compiling on AMD devices (can probably write some wrappers instead of including `*.cc` files for an actual fix)
> Sycl fix nans

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/Makefile
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/Makefile_src
- epochX/cudacpp/ee_mumu.auto/CODEGEN_cudacpp_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.auto/SubProcesses/Makefile
- epochX/cudacpp/ee_mumu.auto/src/Makefile
- epochX/cudacpp/ee_mumu/SubProcesses/Makefile
- epochX/cudacpp/ee_mumu/src/Makefile
- epochX/cudacpp/gg_tt.auto/CODEGEN_cudacpp_gg_tt_log.txt
- epochX/cudacpp/gg_tt.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_tt.auto/src/Makefile
- epochX/cudacpp/gg_tt/SubProcesses/Makefile
- epochX/cudacpp/gg_tt/src/Makefile
- epochX/cudacpp/gg_ttgg.auto/CODEGEN_cudacpp_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_ttgg.auto/src/Makefile
- epochX/cudacpp/gg_ttgg/SubProcesses/Makefile
- epochX/cudacpp/gg_ttgg/src/Makefile
- epochX/cudacpp/tput/logs_eemumu_manu/log_eemumu_manu_d_inl0_hrd0.txt
Test if the code works with -O0 instead of -O3: functional results are ok, but C++ loses a factaor 20 or more in performance!
MInor fix in the 'find' statements to silence errors if 'find' is applied to non existing directories
> Minor tests (-O0) and fixes (find) in Makefile's

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/EventStatistics.h
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
- epochX/cudacpp/CODEGEN/generateAndCompare.sh
- epochX/cudacpp/CODEGEN/syncManu.sh
- epochX/cudacpp/ee_mumu.auto/CODEGEN_cudacpp_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.auto/SubProcesses/EventStatistics.h
- epochX/cudacpp/ee_mumu/SubProcesses/EventStatistics.h
- epochX/cudacpp/gg_tt.auto/CODEGEN_cudacpp_gg_tt_log.txt
- epochX/cudacpp/gg_tt.auto/SubProcesses/EventStatistics.h
- epochX/cudacpp/gg_tt/SubProcesses/EventStatistics.h
- epochX/cudacpp/gg_ttgg.auto/CODEGEN_cudacpp_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.auto/SubProcesses/EventStatistics.h
- epochX/cudacpp/gg_ttgg/SubProcesses/EventStatistics.h
This is a WIP for pptt code generation (#272). I immediately hit the bug reported by @oliviermattelaer in #337.
> Fix assert in pptt code generation

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/rambo.h
- epochX/cudacpp/CODEGEN/syncManu.sh
- epochX/cudacpp/ee_mumu.auto/CODEGEN_cudacpp_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.auto/src/rambo.h
- epochX/cudacpp/ee_mumu/src/rambo.h
- epochX/cudacpp/gg_tt.auto/CODEGEN_cudacpp_gg_tt_log.txt
- epochX/cudacpp/gg_tt.auto/src/rambo.h
- epochX/cudacpp/gg_tt/src/rambo.h
- epochX/cudacpp/gg_ttg.auto/CODEGEN_cudacpp_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.auto/src/rambo.h
- epochX/cudacpp/gg_ttg/src/rambo.h
- epochX/cudacpp/gg_ttgg.auto/CODEGEN_cudacpp_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.auto/src/rambo.h
- epochX/cudacpp/gg_ttgg/src/rambo.h
- epochX/cudacpp/gg_ttggg.auto/CODEGEN_cudacpp_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.auto/src/rambo.h
- epochX/cudacpp/gg_ttggg/src/rambo.h
- epochX/cudacpp/tput/logs_eemumu_manu/log_eemumu_manu_d_inl0_hrd0.txt
- epochX/cudacpp/tput/logs_ggttgg_manu/log_ggttgg_manu_d_inl0_hrd0.txt
This is a followup to PR #365 - I realised there was a better way to get the four momentum o fth efinal particle, just add those of the initial particles, this is more generic, the previous one had buggy physics
> Improved fixes for rambo 2-to-1

- .github/workflows/c-cpp.yml
Do not cancel jobs in a matrix if another job failed
See https://github.community/t/error-the-operation-was-canceled-in-ci/166506/4
See https://stackoverflow.com/questions/61070925/github-actions-disable-auto-cancel-when-job-fails
This is important for the 'shared' PR #367, where I was getting several uncorrelated failures from different sources and I want to see them all
> Disable fail-fast in the github CI

- epochX/alpaka/README.md
The instructions in the README were setting up the madgraph installation with a different relative position compared to the 'madgraph4gpu' directory (the latter containing the command random number generator and the testing tools). There was them some inconsistency with where the Makefile was looking for google test files and the test reference files (e.g. '../../../../../test').
> [alpaka] fix typo and add subdirectory to build instructions in the README.

- epochX/alpaka/CODEGEN/PLUGIN/ALPAKA_CUDACPP_SA_OUTPUT/model_handling.py
This adds 'static' to 3 constexpr in CPPProcess (for cpu/cuda/alpaka builds) generated by the alpaka plugin. Also mentioned in issue #407, this allows the gg->ttggg process to run for alpaka. A similar change (static constexpr) is already present on master for plain cuda, but this was not in the goldenX4 tag on which the alpaka plugin is currently based.
> [alpaka] Add static to several constexpr generated in code for CPPProcess

- .github/workflows/c-cpp.yml
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/Makefile
- epochX/cudacpp/ee_mumu.auto/SubProcesses/Makefile
- epochX/cudacpp/ee_mumu.mad/SubProcesses/Makefile
- epochX/cudacpp/ee_mumu/SubProcesses/Makefile
- epochX/cudacpp/gg_tt.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_tt.mad/SubProcesses/Makefile
- epochX/cudacpp/gg_tt/SubProcesses/Makefile
- epochX/cudacpp/gg_ttg.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_ttg/SubProcesses/Makefile
- epochX/cudacpp/gg_ttgg.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_ttgg/SubProcesses/Makefile
- epochX/cudacpp/gg_ttggg.auto/SubProcesses/Makefile
- epochX/cudacpp/gg_ttggg/SubProcesses/Makefile
If REQUIRE_CUDA is set (to an arbitrary value), the presence of a CUDA
installation is checked at build time.
> [CI] Introduce environment variable REQUIRE_CUDA.

- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.makefile
- epochX/cudacpp/CODEGEN/generateAndCompare.sh
- epochX/cudacpp/ee_mumu.auto/CODEGEN_cudacpp_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/Cards/run_card.dat
- epochX/cudacpp/ee_mumu.mad/Source/run_card.inc
- epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile
- epochX/cudacpp/gg_tt.auto/CODEGEN_cudacpp_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/Cards/run_card.dat
- epochX/cudacpp/gg_tt.mad/Source/run_card.inc
- epochX/cudacpp/gg_tt.mad/SubProcesses/makefile
- epochX/cudacpp/gg_tt.madonly/CODEGEN_madonly_gg_tt_log.txt
- epochX/cudacpp/gg_tt.madonly/Cards/run_card.dat
- epochX/cudacpp/gg_tt.madonly/Source/run_card.inc
- epochX/cudacpp/gg_tt.madonly/SubProcesses/makefile
- epochX/cudacpp/gg_ttg.auto/CODEGEN_cudacpp_gg_ttg_log.txt
- epochX/cudacpp/gg_ttgg.auto/CODEGEN_cudacpp_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttggg.auto/CODEGEN_cudacpp_gg_ttggg_log.txt
This is a PR for #373 and specifically #417.
We can now finally use the full running alphas machinery and get the same physics results in fortran and cudacpp
It also includes a few bug fixes in Makefiles, for bugs I introduced in the previous PR #452
> Enable properly running alphas again (variable renormalization scale) + Makefile fixes

- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.auto_dsig1.f
- epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/auto_dsig1.f
- epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/auto_dsig1.f
- epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/auto_dsig1.f
- epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/auto_dsig1.f
- epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/auto_dsig1.f
- epochX/cudacpp/tmad/logs_eemumu_mad/log_eemumu_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggtt_mad/log_ggtt_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttg_mad/log_ggttg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttgg_mad/log_ggttgg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttggg_mad/log_ggttggg_mad_d_inl0_hrd0.txt
This is a PR addressing #461 - I observed a difference in cudacpp ME throughputs when computed in standalone mode (even in bridge mode) and within cmadevent/gmadevent.
The largest part of the difference (a factor 2, because I only do one iteration in these tests) is due to the fact that I was not removing helicity filtering in the cudacpp timers. So Fortran MEs includes only one ME calculation, while cudacpp includes two (the first one for helicity filtering, the second one for real ME calculation).
This is now fixed in this PR.
> Remove helicity filtering from cudacpp ME timers in (c/g)madevent

- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.P1
- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.auto_dsig1.f
- epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/Source/dsample.f
- epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/auto_dsig1.f
- epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/driver.f
- epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/auto_dsig1.f
- epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/driver.f
- epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/matrix1.f
- epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/auto_dsig1.f
- epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/driver.f
- epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/auto_dsig1.f
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/driver.f
- epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/auto_dsig1.f
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/driver.f
- epochX/cudacpp/tmad/allTees.sh
- epochX/cudacpp/tmad/logs_eemumu_mad/log_eemumu_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggtt_mad/log_ggtt_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttg_mad/log_ggttg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttgg_mad/log_ggttgg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttggg_mad/log_ggttggg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/madX.sh
- epochX/cudacpp/tmad/teeMadX.sh
Hi @oliviermattelaer @roiser 
This WIP PR is a first attempt to produce cross sections and unweighted events using the madevent sampling plus the cudacpp MEs.
A first milestone has been achieved! If I compute BOTH the Fortran and cudacpp MEs (FBRIDGE_MODE=-1), and then I simply replace the Fortran ME by the cudacpp ME, I do get the correct cross sections and numbers of unweighted events (I have not compared event files yet). This was quite trivial to do , I just needed to add one line copying OUT=OUT2 which replaces the fortran ME by the cudacpp ME.
There is still a problem however: if I ONLY compute the cudacpp ME and I skip the Fortran ME calculation (i.e. if I skip SMATRIX1 calls, this is FBRIDGE_MODE=1), then I get several problems: 
- the cross sections in fortran and cudacpp differ …
> First attempt to produce cross sections and events using cudacpp MEs (debug common blocks behind SMATRIX1: add RESET_CUMULATIVE_VARIABLE call)

- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.auto_dsig1.f
- epochX/cudacpp/CODEGEN/patchMad.sh
- epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/SubProcesses/P1_ll_ll/auto_dsig1.f
- epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/SubProcesses/P1_gg_ttx/auto_dsig1.f
- epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.mad/SubProcesses/P1_gg_ttxg/auto_dsig1.f
- epochX/cudacpp/gg_ttg.mad/SubProcesses/addmothers.f
- epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/P1_gg_ttxgg/auto_dsig1.f
- epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/P1_gg_ttxggg/auto_dsig1.f
- epochX/cudacpp/tmad/logs_eemumu_mad/log_eemumu_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggtt_mad/log_ggtt_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttg_mad/log_ggttg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttgg_mad/log_ggttgg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/logs_ggttggg_mad/log_ggttggg_mad_d_inl0_hrd0.txt
- epochX/cudacpp/tmad/madX.sh
This is a workaround for https://github.com/oliviermattelaer/mg5amc_test/issues/14
It is the first step of #402: it implements a dummy color choice (as opposed to a random color choice)
Essentially I have just added JAMP2_MULTI(0,IVEC) = NCOLOR. I have not even initialised JAMP2_MULTI(1:MAXFLOW,IVEC), it seems that addmothers.f manages this by itself somehow
> Next patch for cudacpp-only MEs: add dummy color choice to fix 'failed to reduce to color index' 

- epochX/cudacpp/CODEGEN/MG5aMC_patches/patch.common
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk
- epochX/cudacpp/ee_mumu.mad/CODEGEN_mad_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/ee_mumu.mad/SubProcesses/makefile
- epochX/cudacpp/ee_mumu.sa/CODEGEN_cudacpp_ee_mumu_log.txt
- epochX/cudacpp/ee_mumu.sa/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_tt.mad/CODEGEN_mad_gg_tt_log.txt
- epochX/cudacpp/gg_tt.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_tt.mad/SubProcesses/makefile
- epochX/cudacpp/gg_tt.sa/CODEGEN_cudacpp_gg_tt_log.txt
- epochX/cudacpp/gg_tt.sa/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttg.mad/CODEGEN_mad_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttg.mad/SubProcesses/makefile
- epochX/cudacpp/gg_ttg.sa/CODEGEN_cudacpp_gg_ttg_log.txt
- epochX/cudacpp/gg_ttg.sa/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttgg.mad/CODEGEN_mad_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttgg.mad/SubProcesses/makefile
- epochX/cudacpp/gg_ttgg.sa/CODEGEN_cudacpp_gg_ttgg_log.txt
- epochX/cudacpp/gg_ttgg.sa/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttggg.mad/CODEGEN_mad_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_ttggg.mad/SubProcesses/makefile
- epochX/cudacpp/gg_ttggg.sa/CODEGEN_cudacpp_gg_ttggg_log.txt
- epochX/cudacpp/gg_ttggg.sa/SubProcesses/cudacpp.mk
- epochX/cudacpp/heft_gg_h.sa/CODEGEN_cudacpp_heft_gg_h_log.txt
- epochX/cudacpp/heft_gg_h.sa/SubProcesses/cudacpp.mk
A few fixes for Jorgen on juwels
- #503 fix the behaviour of 'export CUDA_HOME=invalid' for cpp only builds on .mad directories
- #504 allow the use of unsupported compilers if ALLOW_UNSUPPORTED_COMPILER_IN_CUDA is set
- #505 disable CUDA builds (and add other fixes) for multi-word CXX env variables (like clang --gcc-toolchain)
> A few fixes for Jorgen on juwels

- epochX/cudacpp/tput/logs_ggttgg_mad/log_ggttgg_mad_d_inl0_hrd0.txt
- test/Makefile
Compiler tests for Jorgen and minor fixes for bmk
This includes
- the first tests for cuda117 (with gcc11.2)
- a test of cuda115 and gcc112 for juwels
For the bmk I further simplified the googletest makefiles
> Compiler tests for Jorgen and minor fixes for bmk

- epochX/cudacpp/tput/throughputX.sh
Fix bug in throughputX.sh (missing fptype in cpp tests!)
The bug was introduced in 13a8faca40f3cb3afbd4c6b276416ac6c8262f76
> fix bug in throughputX.sh (missing fptype in cpp tests!)

- epochX/alpaka/README.md
Clarify the Alpaka README to say that these tools are required for building:
CUDA version 11.6, g++ 10.2.0, Python 3.8, and Boost 1.78.0.
> In Alpaka README, clarify build requirements

- .github/workflows/c-cpp.yml
In order to move to Alma9, devtoolset-10 had to be disabled, since Alma9 is already at gcc-11.
Cuda was updated to v12.0.
Both concern the GPU part only.
> Move CI to Alma9.

- epochX/cudacpp/CODEGEN/generateAndCompare.sh
Add support for "any" process in generateAndCompare.sh 
Example
```
./CODEGEN/generateAndCompare.sh gg_bb --mad -c 'generate g g > b b~'
```
Error handling
```
[avalassi@itscrd80 gcc11.2/cvmfs] /data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp>  ./CODEGEN/generateAndCompare.sh gg_bb 
...
ERROR! Unknown process 'gg_bb' and no external process specified with '-c <cmd>'
```
and
```
[avalassi@itscrd80 gcc11.2/cvmfs] /data/avalassi/GPU2023/madgraph4gpuX/epochX/cudacpp>  ./CODEGEN/generateAndCompare.sh gg_tt --mad -c 'generate g g > t t~ g g '
...
ERROR! Invalid option '-c <cmd>' to predefined process 'gg_tt'
Predefined cmd='generate g g > t t~'
User-defined cmd='generate g g > t t~ g g g g'
```
> Add support for "any" process in generateAndCompare.sh 

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
override the prepare_couplings function in the in PLUGIN_UFOModelConverter class
the additional functionality will re-order the dictionary keys of the dependent couplings such that they follow the correct ordering. The wanted_couplings parameter of the function contains the correct ordering as it is discovered in the OneProcessExporter class
fixes #748
> WIP: if needed fix the order of couplings 

- epochX/kokkos/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum/makefile
- epochX/kokkos/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx/makefile
- epochX/kokkos/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg/makefile
- epochX/kokkos/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg/makefile
- epochX/kokkos/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg/makefile
because of the parallel existence of a file Makefile (upper case M) this creates a problem on standard MacOS filesystems which is case insensitive.
> remove symbolik links in the .sa directories makefile->kokkos.mk

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
…e base class called "wanted_couplings", this list also contained the independent couplings which need to be removed / filtered out before applying the ordering
> fix running couplings ordering

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/MG5aMC_patches/PROD/patch.common
When using lhapdf there is a fortran wrapper file around it. It includes the coupl.inc include which needs to be prepended with the usual include of vector.inc
This PR adds the corresponding patch to the code generating part of the plugin patching mechanism
> add missing vector.inc to the lhapdf wrapper

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
This fixes a problem when using a model which is sm but not standard, e.g. a line
```
import model sm-no_b_mass
```
would produce an error in the model_handling.py. This PR will fix the problem, but I'm a bit wary about this piece of code in general. I merge this PR anyway now to let our users continue working but I think would be good to discuss this in more depth. I open an issue for it.
> fix a problem when using sm models which are not standard

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp_src.mk
With the latest update of XCode on MacOS the building of the code broke. The linkflags need two extra options "-ld_classic -lstdc++". This fix introduces a variable LDEXTRAFLAGS which will be added to the link statements. The makefiles are currently being worked on by @Jooorgen and @hageboeck with separate PRs, I expect this to vanish anyway soon again with the two PRs merged.
> Fix mac os linking

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
when filtering out the running couplings from wanted_couplings, preserve the order, the trick is to swap the two containers
> preserve order of coupling when filtering dependent ones out

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk
- epochX/cudacpp/gg_tt.mad/SubProcesses/cudacpp.mk
- epochX/cudacpp/gg_tt.mad/src/mgOnGpuConfig.h
When on a machine without a curand library the code would currently not compile, mainly because of check.exe and gcheck.exe. The patches in this PR shall fix this problem. 
NB: There is an #undef MGONGPU_HAS_NO_CURAND in src/mgOnCpuConfig.h which probably also needs to be removed
> support GPU builds without the curand library (incomplete patch)

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/check_sa.cc
in CODEGEN, fix clang format in my previous patch for curand
> in CODEGEN, fix clang format in my previous patch for curand

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/output.py
With Stefan we noticed that 
"output madevent_gpu" was producing a run_card with the default value set for SIMD mode...
This patch is fixing that.
> Fix default run_card for GPU 

- .github/workflows/testsuite_oneprocess.sh
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
Adding a PR (in WIP) to see if the following branch does create issue. 
@valassi do we have a CI test for the missmatch of color?
Because, the point of this PR is to be able to fix such missmatch (I did not tested that part yet).
In particular, I want to test if I did break things for SA side (It would be weird...)
The idea of such patch is to ensure that the datastructure use to write the color (is_LC information) is the same on the fortran and cpp side. 
In the previous code, the function was called twice with two different type of data-structure. I do not understand why this was needed, so I fully removed the first call (which explains why I want to run the CI to check for side effect). (and change the datastructure of the second call)
> ensure that cpp data structure for is_LC is the same in fortran and cpp

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/model_handling.py
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/output.py
This is based on the work of @roiser (thanks so much for it).
Trying to avoid to do what I suggest him to do (i.e. avoiding global variable).
Putting this in PR to have the CI/CD.
Next step here would be to merge my new test to check other problematic process (to see if it was the same issue)
> Couplings order

- .github/workflows/c-cpp.yml
CI fix: move from gfortran-11 to gfortran-14 on Mac github-hosted runners
This is a possible fix for #971
> CI fix: move from gfortran-11 to gfortran-14 on Mac github-hosted runners

- .github/workflows/archiver.sh
- .github/workflows/archiver.yml
- .gitmodules
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/CHANGELOG.md
- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/__init__.py
- epochX/cudacpp/gitTag.sh
Hi @oliviermattelaer this is a small PR to update __init__.py to (1,0,1)
It also fixes the scripts to produce 'v1.00.01' tags (fixing #1013)
Should be non controversial I hope, can you have a look?
Thanks
Andrea
> Update __init__.py to (1,0,1)  and fix 'v1.00.01' tags - also remove untracked warnings for git submodule 

- .github/workflows/testsuite_oneprocess.yml
- tools/mg-clang-format/mg-clang-format
Debug github CI issues with clang-format
See https://github.com/madgraph5/madgraph4gpu/actions/runs/11304784032/job/31443586843
```
+++ Check code formatting in newly generated code ee_mumu.mad
ERROR! clang-format version >= 13 and <= 15 is not installed and /cvmfs/sft.cern.ch/lcg/releases/clang is not reachable
ERROR! mg-clang-format failed
ERROR! Auto-generated code does not respect formatting policies
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[testsuite_oneprocess.sh] codegen (ee_mumu.mad) finished with status=1 (NOT OK) at Sat Oct 12 10:07:47 UTC 2024
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Error: Process completed with exit code 1.
```
> Downgrade oneprocess tests in the CI to ubuntu-22.04 because clang-format-18 is not yet supported

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/launch_plugin.py
In cudacpp.mk, cudacpp_config.mk is included before make_opts. When setting floating_type from the run_card, it is appended to make_opts, but since FPTYPE is set with the "override" directive in cudacpp_config the default value is automatically taken unless FPTYPE is given as a command line argument.
Circumventing this by adding "override" to the make_opts declaration.
Note: Not a perfect fix. Appending FPTYPE using common_run_interface.CommonRunCmd.update_make_opts_full, which adds the declaration to the TOP of make_opts, regardless of the existence of the same argument name further down in the file
> fixed bug where precision wasn't passed properly from the run_card

- epochX/cudacpp/CODEGEN/PLUGIN/CUDACPP_SA_OUTPUT/madgraph/iolibs/template_files/gpu/cudacpp.mk
This fixes #1020 
Please, @roiser have a look at this, I tried [your fix](https://github.com/madgraph5/madgraph4gpu/pull/1034/files) using `HIP_HOME` but it seems it doesn't work in the machine I used (NGT cluster).
> Get rocm lib paths through generic hipconfig command
